name = "twentyfour-realtime"
main = "src/index.js"
compatibility_date = "2024-11-01"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "Room" }]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
