name = "24worker"
main = "src/index.js"
compatibility_date = "2025-07-01"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "Room" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
